import PDFDocument from 'pdfkit';

/**
 * Generate a professional PDF itinerary with pdfkit.
 */
export function buildItineraryPdf({ trip, itinerary }) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margins: { top: 48, bottom: 48, left: 48, right: 48 } });
    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const currency = trip.budget.currency || 'INR';
    const accent = '#0ea5e9';

    // Header
    doc.rect(0, 0, doc.page.width, 96).fill(accent);
    doc.fillColor('#ffffff').fontSize(22).font('Helvetica-Bold').text('TravelMind AI', 48, 28);
    doc.fontSize(11).font('Helvetica').text('AI-Powered Smart Travel Itinerary', 48, 56);

    doc.fillColor('#0f172a').fontSize(18).font('Helvetica-Bold').text(trip.title, 48, 120);
    doc.fontSize(10).font('Helvetica').fillColor('#475569');
    doc.text(
      `${trip.origin ? trip.origin + ' → ' : ''}${trip.destination}  •  ${new Date(trip.startDate).toDateString()} – ${new Date(trip.endDate).toDateString()}`,
      48, 144
    );
    doc.text(
      `Budget: ${currency} ${Number(trip.budget.total).toLocaleString()}  •  Estimated: ${currency} ${Number(
        trip.totalEstimatedCost
      ).toLocaleString()}  •  Travelers: ${trip.travelers?.adults || 1} adults${trip.travelers?.children ? `, ${trip.travelers.children} children` : ''}`,
      48, 160
    );

    let y = 190;

    const ensure = (needed) => {
      if (y + needed > doc.page.height - 60) {
        doc.addPage();
        y = 48;
      }
    };

    // Days
    for (const day of itinerary.days || []) {
      ensure(40);
      doc.fillColor(accent).fontSize(13).font('Helvetica-Bold').text(`Day ${day.dayNumber} — ${new Date(day.date).toDateString()}`, 48, y);
      y += 20;
      for (const act of day.activities || []) {
        ensure(30);
        const label = act.time ? `${act.time}  ` : '';
        const status =
          act.dataStatus === 'live' ? ' [live]' : act.dataStatus === 'unavailable' ? ' [live data unavailable]' : ' [estimate]';
        doc.font('Helvetica-Bold').fillColor('#0f172a').fontSize(9).text(`${label}${act.title}${status}`, 60, y, { width: 460 });
        y += 13;
        if (act.description) {
          doc.font('Helvetica').fillColor('#475569').fontSize(8.5).text(`  ${act.description}`, 60, y, { width: 460 });
          y += 11;
        }
        if (act.cost?.amount) {
          doc.fillColor('#334155').fontSize(8.5).text(`  Cost: ${act.cost.currency || currency} ${act.cost.amount} ${act.cost.isEstimate ? '(estimate)' : ''}`, 60, y, { width: 460 });
          y += 11;
        }
        y += 2;
      }
      y += 10;
    }

    // Budget summary
    ensure(80);
    doc.moveTo(48, y).lineTo(552, y).strokeColor('#e2e8f0').stroke();
    y += 16;
    doc.fillColor('#0f172a').fontSize(12).font('Helvetica-Bold').text('Budget Summary', 48, y);
    y += 16;
    const rows = [
      ['Total Budget', `${currency} ${Number(trip.budget.total).toLocaleString()}`],
      ['Estimated Cost', `${currency} ${Number(trip.totalEstimatedCost).toLocaleString()}`],
      ['Remaining', `${currency} ${Number(trip.budget.total - trip.totalEstimatedCost).toLocaleString()}`],
      ['Money Saved (optimization)', `${currency} ${Number(trip.moneySaved || 0).toLocaleString()}`],
    ];
    for (const [k, v] of rows) {
      ensure(18);
      doc.font('Helvetica').fontSize(9.5).fillColor('#475569').text(k, 60, y);
      doc.font('Helvetica-Bold').fillColor('#0f172a').text(v, 400, y);
      y += 16;
    }

    // Safety & emergency
    if (itinerary.safetyNotes) {
      ensure(50);
      doc.moveTo(48, y).lineTo(552, y).strokeColor('#e2e8f0').stroke();
      y += 16;
      doc.fillColor('#0f172a').fontSize(12).font('Helvetica-Bold').text('Safety Notes', 48, y);
      y += 16;
      doc.font('Helvetica').fontSize(9).fillColor('#475569').text(itinerary.safetyNotes, 60, y, { width: 460 });
      y += 20;
      doc.font('Helvetica-Oblique').fontSize(8).fillColor('#94a3b8').text('For verified emergency numbers, use the Emergency Center in the app.', 60, y, { width: 460 });
    }

    doc.font('Helvetica').fontSize(8).fillColor('#94a3b8').text(
      `Generated by TravelMind AI on ${new Date().toDateString()}. Estimated costs are flagged as estimates; live data is flagged as live.`,
      48, doc.page.height - 36
    );

    doc.end();
  });
}

export default { buildItineraryPdf };
