import React from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import toast from 'react-hot-toast';
import {
  CalendarDays, Download, Wand2, RefreshCw, Compass, FileText, AlertTriangle, Bot,
} from 'lucide-react';
import PageHeader from '../components/ui/PageHeader';
import ItineraryTimeline from '../components/ItineraryTimeline';
import TripSelect from '../components/TripSelect';
import { tripApi } from '../services/apiClient';
import { errorMessage } from '../services/api';
import { PageLoader } from '../components/ui/Spinner';
import EmptyState from '../components/ui/EmptyState';
import Badge from '../components/ui/Badge';
import { formatCurrency } from '../utils/format';
import useTripId from '../hooks/useTripId';

export default function ItineraryPage() {
  const tripId = useTripId();
  const navigate = useNavigate();

  const { data, isLoading, error, refetch, isFetching } = useQuery({
    queryKey: ['itinerary', tripId],
    queryFn: () => tripApi.itinerary(tripId).then((r) => r.data.data),
    enabled: Boolean(tripId),
  });

  if (!tripId) {
    return (
      <div>
        <PageHeader icon={CalendarDays} title="AI Itinerary" subtitle="Your day-by-day plan generated by the agents." />
        <EmptyState
          icon={Compass}
          title="No trips yet"
          message="Generate a trip with the planner and your day-by-day AI itinerary will appear here."
          action={<Link to="/planner" className="btn-primary mt-2"><Compass className="h-4 w-4" /> Plan a trip</Link>}
        />
      </div>
    );
  }

  if (isLoading) return <PageLoader label="Loading itinerary…" />;
  if (error) {
    return (
      <div className="card p-8 text-center">
        <AlertTriangle className="mx-auto h-10 w-10 text-amber-500" />
        <p className="mt-3 font-bold text-slate-900 dark:text-white">Couldn't load the itinerary</p>
        <p className="mt-1 text-sm text-slate-500">{errorMessage(error)}</p>
        <button onClick={() => refetch()} className="btn-secondary mt-4"><RefreshCw className="h-4 w-4" /> Retry</button>
      </div>
    );
  }

  const { trip, itinerary } = data;
  const currency = trip.budget.currency || 'INR';
  const remaining = trip.budget.total - trip.totalEstimatedCost;

  return (
    <div>
      <PageHeader
        icon={CalendarDays}
        title={trip.title}
        subtitle={`${trip.origin ? trip.origin + ' → ' : ''}${trip.destination} · ${new Date(trip.startDate).toDateString()} – ${new Date(trip.endDate).toDateString()}`}
        actions={
          <>
            <TripSelect value={trip._id} onChange={(id) => id && navigate(`/itinerary/${id}`)} />
            <a href={tripApi.pdfUrl(trip._id)} target="_blank" rel="noreferrer" className="btn-secondary">
              <Download className="h-4 w-4" /> PDF
            </a>
            <Link to={`/budget?trip=${trip._id}`} className="btn-secondary">
              <Wand2 className="h-4 w-4" /> Optimize budget
            </Link>
          </>
        }
      />

      {/* Summary strip */}
      <div className="mb-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        <div className="card p-4">
          <p className="text-xs font-semibold uppercase text-slate-400">Total budget</p>
          <p className="mt-1 text-lg font-extrabold text-slate-900 dark:text-white">{formatCurrency(trip.budget.total, currency)}</p>
        </div>
        <div className="card p-4">
          <p className="text-xs font-semibold uppercase text-slate-400">Estimated cost</p>
          <p className="mt-1 text-lg font-extrabold text-slate-900 dark:text-white">{formatCurrency(trip.totalEstimatedCost, currency)}</p>
        </div>
        <div className="card p-4">
          <p className="text-xs font-semibold uppercase text-slate-400">Remaining</p>
          <p className={`mt-1 text-lg font-extrabold ${remaining >= 0 ? 'text-emerald-500' : 'text-rose-500'}`}>
            {formatCurrency(remaining, currency)}
          </p>
        </div>
        <div className="card p-4">
          <p className="text-xs font-semibold uppercase text-slate-400">Validation</p>
          <div className="mt-1.5">
            {itinerary.validation?.passed ? (
              <Badge tone="green">✓ Validated by Final Validator</Badge>
            ) : (
              <Badge tone="amber">{itinerary.validation?.issues?.length || 0} issues found</Badge>
            )}
          </div>
        </div>
      </div>

      {/* Validation warnings */}
      {itinerary.validation?.issues?.length > 0 && (
        <div className="mb-6 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm dark:border-rose-900 dark:bg-rose-950/40">
          <p className="font-bold text-rose-700 dark:text-rose-300">Validator issues</p>
          <ul className="mt-1 list-inside list-disc text-rose-600 dark:text-rose-400">
            {itinerary.validation.issues.slice(0, 5).map((issue, i) => (
              <li key={i}>{issue}</li>
            ))}
          </ul>
        </div>
      )}

      {/* Agent report */}
      {itinerary.agentReport && (
        <details className="mb-6 card p-4 text-sm">
          <summary className="flex cursor-pointer items-center gap-2 font-bold text-slate-700 dark:text-slate-200">
            <Bot className="h-4 w-4 text-brand-600" /> Multi-agent report ({itinerary.agentReport.length} agents)
          </summary>
          <div className="mt-3 grid gap-1.5 sm:grid-cols-2 lg:grid-cols-3">
            {itinerary.agentReport.map((r, i) => (
              <div key={i} className="flex items-center gap-2 rounded-lg bg-slate-50 px-3 py-1.5 text-xs dark:bg-slate-800/60">
                <span className={`h-2 w-2 rounded-full ${r.status === 'success' ? 'bg-emerald-500' : r.status === 'degraded' ? 'bg-amber-500' : 'bg-rose-500'}`} />
                <span className="font-bold capitalize">{r.agent}</span>
                <span className="ml-auto truncate text-slate-400">{r.message}</span>
              </div>
            ))}
          </div>
        </details>
      )}

      <ItineraryTimeline days={itinerary.days} currency={currency} />

      {/* Safety notes */}
      {itinerary.safetyNotes && (
        <div className="card mt-6 p-5">
          <p className="text-sm font-extrabold text-slate-900 dark:text-white">🛡 Safety notes</p>
          <p className="mt-1 text-sm text-slate-600 dark:text-slate-300">{itinerary.safetyNotes}</p>
          <Link to="/emergency" className="btn-secondary mt-3">
            <FileText className="h-4 w-4" /> Emergency Center
          </Link>
        </div>
      )}

      {isFetching && <p className="mt-4 text-center text-xs text-slate-400">Refreshing…</p>}
    </div>
  );
}
